
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
#header decoration

#CDN settings;
bootstrapJS_CDN: https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js
bootstrapCSS_CDN: https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css
jquery_CDN: https://cdn.staticfile.org/jquery/2.2.4/jquery.min.js

# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "INNOVATION IS KING!"
sidebar-avatar: /img/avatar/logo.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- archive
- friends-blog
#- category
# widget behavior
## Archive
archive_type: 'monthly'
show_count: true
## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value
# two level nav menu
navmenu: [
{
   title: "menu1",
   url: "#menu1",
   children: [
   {
       title: "menu1-1",
       url: "#menu1-1"
   },
   {
       title: "menu1-2",
       url: "#menu1-2"
   }
   ]   
},
{
   title: "menu2",
   url: "#menu2",        
},
{
   title: "menu3",
   url: "#menu3",        
},
{
   title: "menu3",
   url: "#",        
},
{
   title: "menu5",
   url: "#",        
}
]


## Friends
friends: [
    {
        title: "ACE theme",
        href: "http://www.sumoon.com"
    }
#    ,
#    {
#        title: "your blog",
#        href: "http://"
#    }
]
##beian 

beian_info: ICP备8888号
